//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddonService
    {
        public int AddonServiceID { get; set; }
        public Nullable<int> AddonServiceTypeId { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string Comments { get; set; }
    
        public virtual AddonServiceType AddonServiceType { get; set; }
        public virtual DBSSTaff DBSSTaff { get; set; }
        public virtual Member Member { get; set; }
    }
}
