//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string SmtpServer { get; set; }
        public Nullable<int> smtpPort { get; set; }
        public string SmtpEmailAddress { get; set; }
        public string SmtpPassword { get; set; }
        public Nullable<decimal> SubscriptionFeeToBeCharged { get; set; }
        public string DefaultEmailMessage { get; set; }
    }
}
