//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBSSTaff
    {
        public DBSSTaff()
        {
            this.AddonServices = new HashSet<AddonService>();
        }
    
        public int DBSStaffID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string DBSNumber { get; set; }
        public string EmailAddress { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<AddonService> AddonServices { get; set; }
    }
}
