//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TopcareNetworkEntities : DbContext
    {
        public TopcareNetworkEntities()
            : base("name=TopcareNetworkEntities")
        {
            Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AddonService> AddonServices { get; set; }
        public DbSet<AddonServiceType> AddonServiceTypes { get; set; }
        public DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public DbSet<DBSSTaff> DBSSTaffs { get; set; }
        public DbSet<MemberAttendance> MemberAttendances { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<MemberSubscriptionsPaid> MemberSubscriptionsPaids { get; set; }
        public DbSet<Nationality> Nationalities { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<NotificationStaff> NotificationStaffs { get; set; }
        public DbSet<NotificationType> NotificationTypes { get; set; }
        public DbSet<PaymentMethod> PaymentMethods { get; set; }
        public DbSet<PreScheduleFollowup> PreScheduleFollowups { get; set; }
        public DbSet<PreScheduleFollowupDetail> PreScheduleFollowupDetails { get; set; }
        public DbSet<ProgrameTimeTemplate> ProgrameTimeTemplates { get; set; }
        public DbSet<RSVPStatu> RSVPStatus { get; set; }
        public DbSet<ScheduleDetail> ScheduleDetails { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<SubscriptionYear> SubscriptionYears { get; set; }
        public DbSet<TeamMember> TeamMembers { get; set; }
        public DbSet<TransportArrangementStatu> TransportArrangementStatus { get; set; }
        public DbSet<TransportationOption> TransportationOptions { get; set; }
        public DbSet<vwMemberAttendance> vwMemberAttendances { get; set; }
        public DbSet<vwPreScheduleFollowup> vwPreScheduleFollowups { get; set; }
        public DbSet<vwScheduleAttendanceForReport> vwScheduleAttendanceForReports { get; set; }
        public DbSet<vwSubscriptionSummary> vwSubscriptionSummaries { get; set; }
    }
}
