//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationStaff
    {
        public int NotificationID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsDisplayed { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> IsEmailNotification { get; set; }
        public Nullable<bool> IsDisplayOnScreenNotification { get; set; }
        public Nullable<bool> IsMobileTextNotification { get; set; }
        public Nullable<System.DateTime> DisplayedDate { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
    }
}
