//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public Nullable<int> NotificationTypeID { get; set; }
        public Nullable<bool> IsVisibility { get; set; }
        public Nullable<int> NotificationYear { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
    }
}
