//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreScheduleFollowup
    {
        public PreScheduleFollowup()
        {
            this.PreScheduleFollowupDetails = new HashSet<PreScheduleFollowupDetail>();
        }
    
        public int PreScheduleFollowupID { get; set; }
        public string FollowupDoneBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ScheduleID { get; set; }
    
        public virtual ICollection<PreScheduleFollowupDetail> PreScheduleFollowupDetails { get; set; }
    }
}
