//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreScheduleFollowupDetail
    {
        public int PreScheduleFollowupDetailID { get; set; }
        public Nullable<int> TransportArrangementStatusID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> RSVPStatusID { get; set; }
        public string PickOffTime { get; set; }
        public string DropOffTime { get; set; }
        public string Comments { get; set; }
        public Nullable<int> PreScheduleFollowupID { get; set; }
        public Nullable<bool> IsTransportBooked { get; set; }
    
        public virtual PreScheduleFollowup PreScheduleFollowup { get; set; }
    }
}
