//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportationOption
    {
        public int TransportationOptionID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> MustHaveMembershipID { get; set; }
        public string NumberToCall { get; set; }
    }
}
