//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPreScheduleFollowup
    {
        public string Name { get; set; }
        public int MemberID { get; set; }
        public int PreScheduleFollowupID { get; set; }
        public Nullable<int> RSVPStatusID { get; set; }
        public string PickOffTime { get; set; }
        public string DropOffTime { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsTransportBooked { get; set; }
        public int PreScheduleFollowupDetailID { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber3 { get; set; }
        public string MemberTransportationID { get; set; }
        public string RSVPStatusDescription { get; set; }
        public string TransportationOptionsDescription { get; set; }
        public Nullable<System.DateTime> ScheduleDateOfEvent { get; set; }
        public Nullable<int> ScheduleID { get; set; }
    }
}
