//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebApplication_TOP_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwScheduleAttendanceForReport
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<bool> HasAttended { get; set; }
        public int MemberID { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
    }
}
